name: witchy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flame: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/game_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

    - assets/images/cards/attack_card_spritesheet.png
    - assets/images/cards/life_card_spritesheet.png
    - assets/images/cards/magic_card_spritesheet.png

    - assets/images/character/character_idle_spritesheet.png
    - assets/images/character/melee_attack_spritesheet.png
    - assets/images/character/magic_attack_spritesheet.png
    - assets/images/character/lightning_spritesheet.png

    - assets/images/enemies/red_slime_idle_spritesheet.png
    - assets/images/enemies/red_eye_idle_spritesheet.png
    - assets/images/enemies/red_ghost_idle_spritesheet.png

    - assets/images/lifes/heart.png

    - assets/images/screen/scenario.png
    - assets/images/screen/cards_display.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
